### ISSUE TITLE
如何添加token

### ISSUE THREAD

**Issue by 12skoko** [XueK66/PF-cq_qq_api#1]
请问如何添加token

**Comment by XueK66** [comment]
抱歉没有及时回复！

目前v1.0.0没有加websocket的token传递功能。
如果需要的话，我可以在后续版本中加上！

**Comment by 12skoko** [comment]
谢谢！我的onebot机器人和mcdr不在同一个服务器上，他们是通过公网连接的，不用token认证的话太不安全了

**Comment by XueK66** [comment]
> 谢谢！我的onebot机器人和mcdr不在同一个服务器上，他们是通过公网连接的，不用token认证的话太不安全了

了解哩，整上！谢谢尝试使用cq_qq_api!
写完了我@你

**Comment by 12skoko** [comment]
好的谢谢！

**Comment by XueK66** [comment]
@12skoko 更新完哩，有什么错误或者问题的话欢迎提出！

可以在 config 中添加 “token”: "xxx" 来加入token。

谢谢你的建议啦！

**Comment by XueK66** [comment]
@12skoko 再滴滴一遍

**Comment by 12skoko** [comment]
谢谢！我明天起来使用

> @12skoko 再滴滴一遍
